import { useSourceSheet } from './use-source-sheet'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, CalendarDays, ClipboardList, History, Pill, Search, ShieldCheck, TriangleAlert } from 'lucide-react'
import { Button } from '../../components/ui/button'
import { activeSession, demoDate, doctor, doctorClinics, queue } from '../dashboard/demo-data'
import { usePatientPreview } from '../patients/patient-preview-context'
import { formatPatientDate, type DirectoryPatient } from '../patients/model'
import { ClinicalPanel, EmptyClinical, LocalSections, Observations, PatientBanner, SourceSheet, type SourceKind } from './ChartShared'
import { chartEvents, chartTabs, encounterPath, filterEvents, findChartPatient, hasClinicalFixture, patientEncounters, type ChartTab } from './model'
import './chart.css'

export function PatientChart({ practiceId, patientId }: { practiceId: string; patientId: string }) {
  const { records } = usePatientPreview()
  const patient = findChartPatient(records, doctorClinics.map(item => item.practiceId), practiceId, patientId)
  return patient ? <ChartContent patient={patient} /> : <ChartUnavailable />
}
export function ChartUnavailable() { return <main className="dashboard" id="main-content" tabIndex={-1}><h1>Record unavailable</h1><p className="chart-source">This patient or encounter is not available in this practice’s demo records.</p><Link className="text-link" to="/patients">Return to My Patients</Link></main> }
function ChartContent({ patient }: { patient: DirectoryPatient }) {
  const navigate = useNavigate()
  const [tab, setTab] = useState<ChartTab>('Overview')
  const { source, openSource, closeSource, restoreSourceFocus } = useSourceSheet()
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All')
  const available = hasClinicalFixture(patient)
  const entry = queue.find(item => item.patient.id === patient.id && item.patient.practiceId === patient.practiceId)
  const events = filterEvents(chartEvents(patient), query, filter)
  return <main id="main-content" className="dashboard chart-workspace" tabIndex={-1}>
    <nav className="chart-breadcrumb" aria-label="Breadcrumb"><Link to={`/patients?practice=${patient.practiceId}`}>My Patients</Link><span>/</span><span>{patient.name}</span></nav>
    <div className="page-heading"><div><h1>Patient chart</h1><p>Reviewing chart · No encounter started</p></div>{available ? <Button onClick={() => navigate(encounterPath(patient, 'EN-DEMO-006'))}>Open unsigned note<ArrowRight aria-hidden="true" /></Button> : null}</div>
    <PatientBanner patient={patient} />
    {patient.practiceId !== activeSession.practiceId ? <p className="chart-scope-note"><ShieldCheck aria-hidden="true" />Viewing {doctorClinics.find(item => item.practiceId === patient.practiceId)?.site}. Hospital A remains your active clinical session.</p> : null}
    <LocalSections name="Chart section" labels={chartTabs} value={tab} onChange={setTab} />
    <div id="clinical-section" role="tabpanel" aria-labelledby={`local-tab-${chartTabs.indexOf(tab)}`}>
      {tab === 'Overview' ? <div className="chart-grid"><div className="chart-stack">
        <ClinicalPanel title="Clinical summary" icon={ClipboardList}><h3>Ongoing problems</h3>{available ? <><p className="chart-caption">Longitudinal problems · Separate from visit diagnoses</p><div className="chart-problem-list">{['Essential hypertension', 'Type 2 diabetes'].map(name => <div key={name}><strong>{name}</strong><span className="badge green">Active</span><span>15 Aug 2026</span></div>)}</div><p className="chart-source">Recorded by {doctor} · Onset and certainty not captured in fixture</p></> : <p className="chart-caption">Problem list unavailable in this demo. Absence of records does not mean no medical conditions.</p>}<h3 className="chart-subheading">History</h3><dl className="chart-history"><div><dt>Medical</dt><dd>{available ? 'Hypertension; type 2 diabetes' : 'Not recorded'}</dd></div><div><dt>Surgical</dt><dd>Not recorded</dd></div><div><dt>Family</dt><dd>Not reviewed</dd></div><div><dt>Social</dt><dd>Not reviewed</dd></div></dl>{available ? <p className="chart-source">Source: Prior consultation · {doctor} · 15 Aug 2026</p> : null}</ClinicalPanel>
        <ClinicalPanel title="Chart activity" icon={History}><label className="chart-search"><Search aria-hidden="true" /><input aria-label="Search chart activity" placeholder="Search chart activity…" value={query} onChange={event => setQuery(event.target.value)} /></label><div className="chart-filters" aria-label="Activity filters">{['All', 'Encounters', 'Results', 'Medications'].map(value => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{value}</button>)}</div><div className="chart-timeline">{events.map(event => <button key={event.id} onClick={() => { if (event.encounterId) navigate(encounterPath(patient, event.encounterId)); else if (event.category === 'Results') openSource('report'); else setTab(event.target) }}><time>{formatPatientDate(event.date)}</time><span><strong>{event.title}</strong><small>{event.detail}</small></span><ArrowRight aria-hidden="true" /></button>)}</div>{!events.length ? <EmptyClinical title={available ? 'No matching activity' : 'Chart activity unavailable'} detail={available ? 'Try another search or activity filter.' : 'No clinical timeline has been supplied for this demo patient.'} /> : null}</ClinicalPanel>
      </div><aside className="chart-stack"><ClinicalPanel title="Today’s visit" icon={CalendarDays}>{entry ? <><div className="chart-visit-title"><h3>{entry.visit}</h3><span className="badge blue">Ready for doctor</span></div><p>Queue #{entry.token} · Appointment · Waiting {entry.wait} min</p><p className="chart-source">Hospital A · Outpatient Clinic<br />{formatPatientDate(demoDate)} · {activeSession.time} PHT<br />{doctor}</p><div className="chart-visit-action"><span>No encounter started</span><Button disabled>Start consultation</Button></div><p className="chart-caption">Starting care requires a connected clinical service.</p></> : <EmptyClinical title="No visit in this snapshot" detail="Chart review does not create a visit or queue entry." />}</ClinicalPanel>
        <Observations available={available} onSource={() => openSource('observations')} />
        <ClinicalPanel title="Needs follow-up" icon={TriangleAlert}>{available ? <><div className="chart-visit-title"><h3>Review uploaded report</h3><span className="badge red">Overdue</span></div><p className="chart-source">Owner: {doctor}<br />Due 11 Sep 2026 · Awaiting clinician review</p><button className="text-link" onClick={() => openSource('report')}>Open source record<ArrowRight aria-hidden="true" /></button></> : <p className="chart-caption">Follow-up records unavailable in this demo.</p>}</ClinicalPanel>
        <ClinicalPanel title="Medications" icon={Pill}><p>{available ? '2 reported medicines · Reconciliation due' : 'Medication history unavailable'}</p><button className="text-link chart-source-link" onClick={() => setTab('Medications')}>View medication list<ArrowRight aria-hidden="true" /></button></ClinicalPanel>
      </aside></div> : <ChartSection section={tab} patient={patient} onSource={openSource} />}
    </div><footer className="dashboard-footer"><span><ShieldCheck aria-hidden="true" />Practice-scoped chart · Synthetic data</span><span>No server connection</span></footer>
    <SourceSheet onRestoreFocus={restoreSourceFocus} kind={source} patient={patient} onClose={closeSource} />
  </main>
}
export function ChartSection({ section, patient, onSource }: { section: string; patient: DirectoryPatient; onSource: (kind: SourceKind) => void }) {
  const available = hasClinicalFixture(patient)
  if (section === 'Encounters') return <ClinicalPanel title="Encounters"><p className="chart-caption">Care completion and note signing are separate. Historical records retain their original author and release.</p>{patientEncounters(patient).map(item => <div className="chart-record-row" key={item.id}><div><h3>{item.reason}</h3><p>{formatPatientDate(item.date)} · {item.id} · {doctor}</p><div className="chart-statuses"><span className="badge neutral">Care: {item.care}</span><span className={`badge ${item.documentation === 'Draft' ? 'amber' : 'green'}`}>Note: {item.documentation}</span></div></div><Link className="text-link" to={encounterPath(patient, item.id)}>{item.documentation === 'Draft' ? 'Open draft' : 'View signed note'}<ArrowRight aria-hidden="true" /></Link></div>)}{!available ? <EmptyClinical title="Encounter records unavailable" detail="Directory visit dates do not contain clinical notes. No encounter was created by opening this chart." /> : null}<div className="chart-visit-action"><Button variant="outline" disabled>New non-queued encounter</Button><p className="chart-caption">New care requires server confirmation.</p></div></ClinicalPanel>
  if (section === 'Medications') return <ClinicalPanel title="Medication history" icon={Pill}><p className="chart-caption">Reported use is separate from prescribing. Opening this list does not complete reconciliation.</p>{available ? <>{['Losartan', 'Metformin'].map(name => <div className="chart-record-row" key={name}><div><h3>{name}</h3><p>Patient reported · 15 Aug 2026 · Use not verified</p><p>Strength, dose, route and frequency not recorded in fixture</p></div><span className="badge amber">Review due</span></div>)}<p className="chart-source">Collected during prior consultation · {doctor}</p><Button className="chart-disabled-action" disabled>Confirm reconciliation</Button><p className="chart-caption">Reconciliation and prescription issuance require a connected service.</p></> : <EmptyClinical title="Medication history unavailable" detail="No reviewed medication list is available for this demo patient." />}</ClinicalPanel>
  if (section === 'Orders & Results' || section === 'Documents') return <ClinicalPanel title={section}>{available ? <><div className="chart-record-row"><div><h3>External laboratory report</h3><p>Received 11 Sep 2026 · Original attachment unavailable</p><p>Owner: {doctor}</p><span className="badge amber">Awaiting clinician review</span></div><Button variant="outline" onClick={() => onSource('report')}>Open report details</Button></div><p className="chart-caption">This demo contains metadata only. No verified result values, orders or downloadable documents are available.</p></> : <EmptyClinical title={`${section} unavailable`} detail="No source records are included for this patient in the demo." />}</ClinicalPanel>
  if (section === 'Care Plan') return <ClinicalPanel title="Care plan & follow-up">{available ? <><div className="chart-record-row"><div><h3>Review uploaded report</h3><p>Owner: {doctor} · Due 11 Sep 2026</p><span className="badge red">Overdue · Awaiting review</span></div><Button variant="outline" onClick={() => onSource('report')}>Open source record</Button></div><p className="chart-caption">No additional care plans, preventive care or immunization fixtures are available. This task remains open.</p></> : <EmptyClinical title="Care plan unavailable" detail="No care plan or follow-up fixtures are supplied for this patient." />}</ClinicalPanel>
  if (section === 'Patient Details') return <ClinicalPanel title="Patient details"><dl className="chart-history"><div><dt>Full name</dt><dd>{patient.name}</dd></div><div><dt>Record number</dt><dd>{patient.mrn}</dd></div><div><dt>Date of birth</dt><dd>{patient.birthDateAccuracy === 'estimated' ? 'Estimated ' : ''}{formatPatientDate(patient.birthDate)}</dd></div><div><dt>Sex</dt><dd>{patient.sex}</dd></div><div><dt>City</dt><dd>{patient.city ?? 'Not recorded'}</dd></div><div><dt>Identity status</dt><dd>{patient.identity === 'provisional' ? 'Provisional · Verification required' : 'Recorded'}</dd></div></dl><Link className="text-link chart-source-link" to={`/patients/${patient.practiceId}/${patient.id}/edit`}>Edit patient details<ArrowRight aria-hidden="true" /></Link></ClinicalPanel>
  return <ClinicalPanel title="Referrals"><EmptyClinical title="Referral records unavailable" detail="No incoming or outgoing referral fixtures are available for this patient. This does not establish an absence of referrals." /></ClinicalPanel>
}
